name: Atualizar Pluto BR

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clonar Pluto Scraper
        run: |
          git clone https://github.com/evoactivity/pluto-tv.git

      - name: Gerar lista Pluto BR
        run: |
          cd pluto-tv
          npm install
          node index.js br
          cp br.m3u8 ../pluto_br.m3u8

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Organizar lista
        run: python organizar_pluto.py

      - name: Commit e push
        run: |
          git config --global user.name "hermens16"
          git config --global user.email "hermens16@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática diária" || echo "Sem mudanças"
          git push
